//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.asistencia = new HashSet<asistencia>();
            this.detalle_venta = new HashSet<detalle_venta>();
            this.detalle_ingreso = new HashSet<detalle_ingreso>();
            this.kardex = new HashSet<kardex>();
            this.lectura = new HashSet<lectura>();
        }
    
        public int id { get; set; }
        public int grupo_id { get; set; }
        public int unidad_medida_id { get; set; }
        public int impuesto_id { get; set; }
        public int marca_id { get; set; }
        public string clase { get; set; }
        public string nombre_completo { get; set; }
        public string nombre_corto { get; set; }
        public string numero { get; set; }
        public string codigo_auxiliar { get; set; }
        public string codigo_barras { get; set; }
        public Nullable<int> numero_abreviacion { get; set; }
        public Nullable<int> proveedor_preferente { get; set; }
        public string descripcion { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string tiene_promocion { get; set; }
        public string visualizar_venta { get; set; }
        public string estado { get; set; }
        public string observacion_estado { get; set; }
        public string control_stock { get; set; }
        public Nullable<sbyte> stock_minimo { get; set; }
        public Nullable<sbyte> stock_actual { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<int> cci { get; set; }
        public Nullable<System.DateTime> ccd { get; set; }
        public Nullable<int> cwi { get; set; }
        public Nullable<System.DateTime> cwd { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual impuesto impuesto { get; set; }
        public virtual marca marca { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ingreso> detalle_ingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kardex> kardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura> lectura { get; set; }
    }
}
