//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalle_venta()
        {
            this.detalle_asistencia = new HashSet<detalle_asistencia>();
            this.lectura = new HashSet<lectura>();
        }
    
        public int id { get; set; }
        public int venta_id { get; set; }
        public int articulo_id { get; set; }
        public decimal cantidad { get; set; }
        public string detalle { get; set; }
        public decimal valor_unitario { get; set; }
        public decimal valor_total { get; set; }
        public string tipo { get; set; }
    
        public virtual articulo articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_asistencia> detalle_asistencia { get; set; }
        public virtual venta venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura> lectura { get; set; }
    }
}
