//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_kardex
    {
        public int id { get; set; }
        public int kardex_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public Nullable<int> compra_venta_id { get; set; }
        public string numero_factura { get; set; }
        public Nullable<decimal> cantidad_entrada { get; set; }
        public Nullable<decimal> valor_unitario_entrada { get; set; }
        public Nullable<decimal> valor_total_entrada { get; set; }
        public Nullable<decimal> cantidad_salida { get; set; }
        public Nullable<decimal> valor_unitario_salida { get; set; }
        public Nullable<decimal> valor_total_salida { get; set; }
        public Nullable<decimal> cantidad_saldo { get; set; }
        public Nullable<decimal> valor_unitario_saldo { get; set; }
        public Nullable<decimal> valor_total_saldo { get; set; }
    
        public virtual kardex kardex { get; set; }
    }
}
