//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ingreso
    {
        public int id { get; set; }
        public int ingreso_id { get; set; }
        public int articulo_id { get; set; }
        public decimal valor_unitario { get; set; }
        public decimal cantidad { get; set; }
        public decimal valor_total { get; set; }
        public string serie { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual ingreso ingreso { get; set; }
    }
}
