//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class kardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kardex()
        {
            this.detalle_kardex = new HashSet<detalle_kardex>();
        }
    
        public int id { get; set; }
        public int articulo_id { get; set; }
        public string stock { get; set; }
        public int stock_minimo { get; set; }
        public int stock_maximo { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<decimal> precio_mayorista { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
    
        public virtual articulo articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_kardex> detalle_kardex { get; set; }
    }
}
