//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class lectura
    {
        public int id { get; set; }
        public int medidor_id { get; set; }
        public int usuario_id { get; set; }
        public int mes_id { get; set; }
        public int articulo_id { get; set; }
        public Nullable<int> detalle_venta_id { get; set; }
        public string lectura_anterior { get; set; }
        public string lectura_actual { get; set; }
        public Nullable<decimal> consumo { get; set; }
        public string anio { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> valor_base { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string estado { get; set; }
        public Nullable<sbyte> cantidad_exceso { get; set; }
        public string exceso { get; set; }
        public Nullable<decimal> multa_exceso { get; set; }
        public Nullable<decimal> multa_atraso { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<int> cci { get; set; }
        public Nullable<System.DateTime> ccd { get; set; }
        public Nullable<int> cwi { get; set; }
        public Nullable<System.DateTime> cwd { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual detalle_venta detalle_venta { get; set; }
        public virtual medidor medidor { get; set; }
        public virtual mes mes { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
