//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ipwebec_hydrosEntities : DbContext
    {
        public ipwebec_hydrosEntities()
            : base("name=ipwebec_hydrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<asistencia> asistencia { get; set; }
        public virtual DbSet<barrio> barrio { get; set; }
        public virtual DbSet<categoria_menu> categoria_menu { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<costo_tarifa> costo_tarifa { get; set; }
        public virtual DbSet<detalle_asistencia> detalle_asistencia { get; set; }
        public virtual DbSet<detalle_ingreso> detalle_ingreso { get; set; }
        public virtual DbSet<detalle_kardex> detalle_kardex { get; set; }
        public virtual DbSet<detalle_venta> detalle_venta { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<forma_pago> forma_pago { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<impuesto> impuesto { get; set; }
        public virtual DbSet<ingreso> ingreso { get; set; }
        public virtual DbSet<kardex> kardex { get; set; }
        public virtual DbSet<lectura> lectura { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<medidor> medidor { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<mes> mes { get; set; }
        public virtual DbSet<multa_retraso> multa_retraso { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<perfil_menu> perfil_menu { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<tarifa> tarifa { get; set; }
        public virtual DbSet<tipo_comprobante> tipo_comprobante { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<unidad_medida> unidad_medida { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
    }
}
