//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_menu
    {
        public int id { get; set; }
        public int perfil_id { get; set; }
        public int menu_id { get; set; }
        public string autorizacion { get; set; }
        public string escritura { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual perfil perfil { get; set; }
    }
}
