//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.lectura = new HashSet<lectura>();
            this.perfil = new HashSet<perfil>();
        }
    
        public int id { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string tipo_identificacion { get; set; }
        public string numero_identificacion { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string telefono_fijo { get; set; }
        public string telefono_movil { get; set; }
        public string email { get; set; }
        public string foto { get; set; }
        public string direccion { get; set; }
        public string es_superadmin { get; set; }
        public string usuario1 { get; set; }
        public string clave { get; set; }
        public string estado { get; set; }
        public Nullable<int> cci { get; set; }
        public Nullable<System.DateTime> ccd { get; set; }
        public Nullable<int> cwi { get; set; }
        public Nullable<System.DateTime> cwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lectura> lectura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfil> perfil { get; set; }
    }
}
