//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int id { get; set; }
        public int forma_pago_id { get; set; }
        public int tipo_comprobante_id { get; set; }
        public int cliente_id { get; set; }
        public Nullable<int> numero { get; set; }
        public string fecha { get; set; }
        public string orden { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> valor_iva { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public Nullable<int> cci { get; set; }
        public Nullable<System.DateTime> ccd { get; set; }
        public Nullable<int> cwi { get; set; }
        public Nullable<System.DateTime> cwd { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        public virtual forma_pago forma_pago { get; set; }
        public virtual tipo_comprobante tipo_comprobante { get; set; }
    }
}
